[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}, { access = "write", path = "./data/"}]
auto_detect_solc = true
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
bsc = "${BSC_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
linea = "${LINEA_RPC_URL}"
blast = "${BLAST_RPC_URL}"
celo = "${CELO_RPC_URL}"
zksync = "${ZKSYNC_RPC_URL}"
mantle = "${MANTLE_RPC_URL}"
opbnb = "${OPBNB_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
sei = "${SEI_RPC_URL}"
palm = "${PALM_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"

[profile.ci]
fuzz = { runs = 256 }
verbosity = 4
