[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}, { access = "write", path = "./data/"}]
auto_detect_solc = true
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"
optimism = "https://mainnet.optimism.io"
polygon = "https://polygon-rpc.com"
bsc = "https://bsc-dataseed.binance.org"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fantom = "https://rpc.ftm.tools"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"

[profile.ci]
fuzz = { runs = 256 }
verbosity = 4
